import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Sidebar from "@/components/ui/sidebar";
import { Toaster } from "@/components/ui/toaster";
import MobileHeader from "@/components/ui/mobile-header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Test Task",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen w-full bg-white text-black flex overflow-hidden",
          inter.className,
          { "debug-screens": process.env.NODE_ENV === "development" }
        )}
      >
        <MobileHeader />
        {/* Sidebar */}
        <div className="hidden md:block">
          <Sidebar />
        </div>

        {/* main page */}
        <div className="p-8 w-full">
          <Toaster/>
          {children}</div>
      </body>
    </html>
  );
}
